kind: ConfigMap
apiVersion: v1
metadata:
  name: swagger-proxy-service
data:
  application.yml: |-
    spring:
      application:
        name: swagger-proxy-service
    server:
      port: 8083
    zuul:
      routes:
        myalpha:
          path: /myalpha/**
        mybeta:
          path: /mybeta/**
