kind: Service
apiVersion: v1
metadata:
  name: alpha-service
spec:
  selector:
    app: alpha-service
  ports:
    - protocol: TCP
      port: 9191
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-service
spec:
  selector:
    matchLabels:
      app: alpha-service
  replicas: 1
  template:
    metadata:
      labels:
        app: alpha-service
    spec:
      containers:
        - name: alpha-service
          image: springio/alpha-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9191