kind: Service
apiVersion: v1
metadata:
  name: myalpha
spec:
  selector:
    app: myalpha
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myalpha
spec:
  selector:
    matchLabels:
      app: myalpha
  replicas: 1
  template:
    metadata:
      labels:
        app: myalpha
    spec:
      containers:
        - name: myalpha
          image: springio/myalpha:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081