kind: Service
apiVersion: v1
metadata:
  name: mybeta
spec:
  selector:
    app: mybeta
  ports:
    - protocol: TCP
      port: 8082
      nodePort: 30084
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybeta
spec:
  selector:
    matchLabels:
      app: mybeta
  replicas: 1
  template:
    metadata:
      labels:
        app: mybeta
    spec:
      containers:
        - name: mybeta
          image: springio/mybeta:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082